# CAP, single 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("cap03.tst");

# doc/_Chapter_Examples_and_Tests.xml:77-88
gap> LoadPackage( "CAP", false );
true
gap> DummyCommutativeSemiring( );
Dummy commutative semiring 1
gap> DummyCommutativeSemiring( );
Dummy commutative semiring 2
gap> IsSemiring( DummyCommutativeSemiring( ) );
true
gap> IsCommutative( DummyCommutativeSemiring( ) );
true

#
gap> STOP_TEST("cap03.tst", 1);
