# nofoma, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nofoma03.tst");

# doc/_Chapter_Auxiliary_functions.xml:21-30
gap> x:=X(Rationals);;
gap> a:=x^2*(x-1)^3*(x-2)*(x-3);
x_1^7-8*x_1^6+24*x_1^5-34*x_1^4+23*x_1^3-6*x_1^2
gap> b:=x^2*(x-1)^2*(x-2)^4*(x-4);
x_1^9-14*x_1^8+81*x_1^7-252*x_1^6+456*x_1^5-480*x_1^4+272*x_1^3-64*x_1^2
gap> GcdCoprimeSplit(a,b);
[ x_1^5-4*x_1^4+5*x_1^3-2*x_1^2, x_1^4-6*x_1^3+12*x_1^2-10*x_1+3, 
  x_1^7-12*x_1^6+56*x_1^5-128*x_1^4+144*x_1^3-64*x_1^2 ]

# doc/_Chapter_Auxiliary_functions.xml:42-52
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 0, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> x:=X(Rationals);;
gap> pol:=x^6-6*x^5+12*x^4-10*x^3+3*x^2;;
gap> v:=[ 1, 1, 1, 1 ];;
gap> PolynomialToMatVec(A,pol,v);
[ 8, -16, 8, -16 ]

# doc/_Chapter_Auxiliary_functions.xml:93-113
gap> A:=[ [   5,   2,  -4,   2 ],
>         [  -1,   0,   2,  -1 ],
>         [  -1,  -1,   3,  -1 ],
>         [ -13,  -7,  14,  -6 ] ];;
gap> SpinMatVector(A,[1,0,0,0]);
[ [ [ 1, 0, 0, 0 ], [ 0, 1, -2, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 5, 2, -4, 2 ] ],
  [ -1, 0, 1 ],
  [ 1, 2 ] ]
gap> SpinMatVector(A,[0,1,0,0]);
[ [ [ 0, 1, 0, 0 ], [ 1, 0, -2, 1 ], [ 0, 0, 1, -1/2 ] ],
  [ [ 0, 1, 0, 0 ], [ -1, 0, 2, -1 ], [ 6, 3, -4, 2 ] ],
  [ 1, -1, -1, 1 ],
  [ 2, 1, 3 ] ]
gap> SpinMatVector(A,[1,1,0,0]);
[ [ [ 1, 1, 0, 0 ], [ 0, 1, 1, -1/2 ] ],
  [ [ 1, 1, 0, 0 ], [ 4, 2, -2, 1 ] ],
  [ 1, -2, 1 ],
  [ 1, 2 ] ]

# doc/_Chapter_Auxiliary_functions.xml:128-142
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 1, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> sp:=CyclicChainMat(A);
[ [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 1, 1, 2, 1 ], [ 0, 0, 0, 1 ] ],
  [ 1, 4, 5 ] ]
gap> PrintArray(sp[2]*A*sp[2]^-1);
[ [    0,    1,    0,    0 ],
  [    0,    0,    1,    0 ],
  [    0,    3,    1,    0 ],
  [  1/2,  1/2,  1/2,    0 ] ]

# doc/_Chapter_Auxiliary_functions.xml:167-180
gap> A:=[ [  2,  2,  0,  1,  0,  2,  1 ],
>         [  0,  4,  0,  0,  0,  1,  0 ],
>         [  0,  1,  1,  0,  0,  1,  1 ],
>         [  0, -1,  0,  1,  0, -1,  0 ],
>         [  0, -7,  0,  0,  1, -5,  0 ],
>         [  0, -2,  0,  0,  0,  1,  0 ],
>         [  0, -1,  0,  0,  0, -1,  1 ] ];;
gap> MaximalVectorMat(A);
[ [ 1, -2, 1, 1, 0, 0, 1 ], x_1^4-7*x_1^3+17*x_1^2-17*x_1+6 ]
gap> v:=last[1];;
gap> SpinMatVector(A,v)[3];
[ 6, -17, 17, -7, 1 ]

# doc/_Chapter_Auxiliary_functions.xml:227-238
gap> v:=[ 1, 1, 1, 1 ];;
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 1, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> PrintArray(RatFormStep1(A,v)[1]);
[ [  0,  1,  0,  0 ],
  [  0,  0,  1,  0 ],
  [  0,  3,  1,  0 ],
  [  1,  0,  0,  0 ] ]

#
gap> STOP_TEST("nofoma03.tst", 1);
