# nofoma, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nofoma02.tst");

# doc/_Chapter_Other_functionality.xml:24-47
gap> A:=[ [  6, -2,  6,  1,  1 ],
>         [  1, -1,  2,  1, -2 ],
>         [ -2,  0, -1,  0, -1 ],
>         [ -1,  0, -2,  2, -1 ],
>         [ -4,  4, -6, -2,  3 ] ];;
gap> jc:=JordanChevalleyDecMat(A,MinimalPolynomial(A));
[ [ [  4,  0,  4, -1,  1 ], 
    [  1,  0,  1,  1, -1 ], 
    [ -1, -1,  0,  1, -1 ], 
    [  0,  0, -2,  3,  0 ], 
    [ -3,  2, -4, -1,  2 ] ], 
  [ [  2, -2,  2,  2,  0 ], 
    [  0, -1,  1,  0, -1 ], 
    [ -1,  1, -1, -1,  0 ], 
    [ -1,  0,  0, -1, -1 ], 
    [ -1,  2, -2, -1,  1 ] ] ]
gap> MinimalPolynomial(jc[1]);
x_1^3-5*x_1^2+9*x_1-5
gap> Factors(last);
[ x_1-1, x_1^2-4*x_1+5 ]  
gap> MinimalPolynomial(jc[2]);
x_1^2                     

# doc/_Chapter_Other_functionality.xml:82-98
gap> A := [ [ Z(5)^2, 0*Z(5), Z(5)^2, Z(5)^3, Z(5) ], 
>    [ 0*Z(5), 0*Z(5), Z(5)^3, Z(5), Z(5)^0 ],  
>    [ Z(5), Z(5)^0, 0*Z(5), Z(5)^0, 0*Z(5) ],
>    [ Z(5)^0, Z(5)^0, Z(5)^0, 0*Z(5), Z(5)^3 ],
>    [ Z(5), 0*Z(5), Z(5)^3, 0*Z(5), Z(5)^3 ] ];;
gap> B := PrimaryDecomposition(A);;
gap> Display(B[3]);
[ 1, 4 ]
gap> Factors(MinimalPolynomial(A));
[ x_1-Z(5)^0, x_1^4-x_1^3+Z(5)^3*x_1+Z(5)^3 ]
gap> PrimA := A^Inverse(B[1]);;
gap> MinimalPolynomial(PrimA{[1..1]}{[1..1]});
x_1-Z(5)^0
gap> MinimalPolynomial(PrimA{[2..5]}{[2..5]});
x_1^4-x_1^3+Z(5)^3*x_1+Z(5)^3

#
gap> STOP_TEST("nofoma02.tst", 1);
